# Generated by Django 2.2.9 on 2020-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djsuperadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
