# Generated by Django 2.2.6 on 2019-10-04 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('djsuperadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'permissions': (('read_content', 'Can read content'),),
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BreadcrumbContentTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('content', models.CharField(max_length=256)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djsuperadmin.BreadcrumbContent')),
            ],
            options={
                'db_table': 'djsuperadmin_breadcrumbcontent_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
        ),
    ]
